<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="STIPLGGNL044" ignored="2" name="Default test(failed)(failed)" tests="1" failures="1" timestamp="21 Feb 2017 09:55:49 GMT" time="119.453" errors="0">
  <testcase name="Create_New_Opportunity" time="90.906" classname="testClasses.Aria.Verify_UserisabletoCommitOpportunity">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utils.BasePage.writeTextInto(BasePage.java:82)
	at actions.AccountsPageActions.create_new_Opportunity(AccountsPageActions.java:57)
	at testClasses.Aria.Verify_UserisabletoCommitOpportunity.Create_New_Opportunity(Verify_UserisabletoCommitOpportunity.java:60)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Create_New_Opportunity -->
  <testcase name="Create_New_Account" time="0.0" classname="testClasses.Aria.Verify_UserisabletoCommitOpportunity">
    <ignored/>
  </testcase> <!-- Create_New_Account -->
  <testcase name="Verify_Login_in_Salesforce" time="0.0" classname="testClasses.Aria.Verify_UserisabletoCommitOpportunity">
    <ignored/>
  </testcase> <!-- Verify_Login_in_Salesforce -->
</testsuite> <!-- Default test(failed)(failed) -->
